# Generated by Django 4.2 on 2023-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirdInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_EN", models.CharField(max_length=128)),
                ("name_CN", models.CharField(max_length=128)),
                ("wiki_link", models.CharField(max_length=256)),
                ("image_link", models.CharField(max_length=256)),
            ],
        ),
    ]
